### ISSUE TITLE
How did you use notion_create_page

### ISSUE THREAD

**Issue by Nucliur** [doutv/Auto-GPT-Notion#1]
AutoGPT keeps using `Write_to_File` instead of `notion_create_page`
**
![image](https://user-images.githubusercontent.com/93684674/235328182-ff7ae47b-8136-4c6a-b948-22e8ac780015.png)
**

I have downloaded the plugin to autoGPT>plugins and installed all dependencies.

How do I solve this?

**Comment by doutv** [comment]
Can you show your `ai_settings.yaml`?

You can walk through demo section in README.
1. Make sure you enable notion plugin.
![image](https://user-images.githubusercontent.com/20609724/235388982-bf915bcd-7d73-4e76-8cf1-65ad72041c07.png)
2. Try my `ai_setttings.yaml`:
  ```yaml
  # ai_settings.yaml
  ai_goals:
  - Use "google" command to search what is Auto-GPT, and save the result to a Notion page
  ai_name: Notion-GPT
  ai_role: Research assistant
  ```
